#Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. 

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [1]:
# your code is here
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [7]:
# your code is here
i = np.array([1,2,3,4,5,6])
i

array([1, 2, 3, 4, 5, 6])

### Task: Create a numpy array of size 6, filled with zeros

In [8]:
# your code is here
i = np.zeros(6)
i

array([0., 0., 0., 0., 0., 0.])

###Task: Create a numpy array of size 6, filled with ones

In [9]:
# your code is here
i = np.ones(6)
i

array([1., 1., 1., 1., 1., 1.])

###Task: Create a numpy array with values from 0 to 10

In [11]:
# your code is here
i = np.array(range(0,11))
i
j = np.arange(0,11)
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [13]:
# your code is here
i = np.ones((2,3))
i

array([[1., 1., 1.],
       [1., 1., 1.]])

###Task: Create a numpy matrix of 3*2 integers, filled with ones

In [15]:
# your code is here
i = np.ones((3,2))
i

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

###Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [17]:
# your code is here
i = np.random.randint(0,10,(3,2))
i

array([[1, 2],
       [0, 5],
       [4, 5]])

###Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [18]:
# your code is here
i = np.random.random((100,2))
i

array([[0.46640598, 0.34130827],
       [0.1121393 , 0.93206945],
       [0.77515539, 0.37652793],
       [0.81084232, 0.91547817],
       [0.03174419, 0.49042847],
       [0.48119803, 0.42974804],
       [0.60027136, 0.23765037],
       [0.35823916, 0.93235209],
       [0.94476647, 0.47953328],
       [0.64350078, 0.86419637],
       [0.15120406, 0.74546464],
       [0.72306688, 0.8281349 ],
       [0.36572116, 0.57559807],
       [0.82668058, 0.47307379],
       [0.38935219, 0.37481672],
       [0.8329688 , 0.30877918],
       [0.34782901, 0.44440617],
       [0.43373336, 0.27770258],
       [0.99659353, 0.30091242],
       [0.28690934, 0.57713503],
       [0.5565994 , 0.01531381],
       [0.81517393, 0.9921456 ],
       [0.81958788, 0.10228423],
       [0.46028484, 0.31091666],
       [0.02740439, 0.1644496 ],
       [0.00954882, 0.98966527],
       [0.61012217, 0.07728593],
       [0.05865494, 0.53486215],
       [0.29944024, 0.57113195],
       [0.71415571, 0.07640804],
       [0.

###Task: Create a numpy matrix of 2 * 3 * 4, filled with integers from 1 to 24.

In [24]:
# your code is here
i = np.arange(1,25).reshape(2,3,4)
i

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [25]:
# your code is here
x = np.array([1,2,3,4,5])

### Task: Show the first element of X

In [26]:
# your code is here
x[0]

1

### Task: Show the last element of X

In [27]:
# your code is here
x[-1]

5

### Task: Show the first 3 elements of X

In [28]:
# your code is here
x[:3]

array([1, 2, 3])

###Task: Show the last 3 elements of X

In [29]:
# your code is here
x[-3:]

array([3, 4, 5])

###Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [30]:
# your code is here
x[::2]

array([1, 3, 5])

###Task: Show the elements of X except the last one

In [31]:
# your code is here
x[:-1]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [33]:
# your code is here
x = np.arange(0,12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###Task: Show the first row of X

In [35]:
# your code is here
x[0]

array([0, 1, 2, 3])

###Task: Show the first column of X

In [38]:
# your code is here
x[:,0]

array([0, 4, 8])

###Task: Show the first element of the first row of X

In [40]:
# your code is here
x[0][0]
x[0,0]

0

###Task: Show the last row of X

In [41]:
# your code is here
x[-1]

array([ 8,  9, 10, 11])

###Task: Show the last column of X

In [42]:
# your code is here
x[:,-1]

array([ 3,  7, 11])

###Task: Show the last element of the last row of X

In [43]:
# your code is here
x[-1,-1]

11

###Task: Show all the rows except the last row of X

In [46]:
# your code is here
x[:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

###Task: Show all the columns except the last column of X

In [48]:
# your code is here
x[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Task: Show the first two elements of the first two rows

In [49]:
# your code is here
x[:2,:2]

array([[0, 1],
       [4, 5]])

## Array Statistics

###Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [56]:
# your code is here
print(np.sum(x), np.mean(x), np.std(x), np.var(x), np.max(x), np.min(x))

55 5.5 2.8722813232690143 8.25 10 1


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [59]:
# your code is here
x = np.arange(1,13).reshape(4,3)
x
print(np.sum(x[0]), np.mean(x[0]), np.std(x[0]), np.var(x[0]), np.max(x[0]), np.min(x[0]))

6 2.0 0.816496580927726 0.6666666666666666 3 1


###Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [60]:
# your code is here
x = np.arange(1,13).reshape(3,4)
x
print(np.sum(x[:,0]), np.mean(x[:,0]), np.std(x[:,0]), np.var(x[:,0]), np.max(x[:,0]), np.min(x[:,0]))

15 5.0 3.265986323710904 10.666666666666666 9 1


## Array Linear Algebra

###Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc. 

In [66]:
# your code is here
x = np.array([[1,2],
             [7,8]])

y = np.array([[3,4],
             [4,5]])

array([[1, 7],
       [2, 8]])