### NumPy

In [8]:
import numpy as np

In [9]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [10]:
a = np.array([0,1,2,3])
type(a)

numpy.ndarray

In [11]:
a.shape

(4,)

In [12]:
a[0]

0

In [13]:
a[3]

3

In [14]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [15]:
a[-1]

3

In [16]:
a[-4]

0

In [17]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [18]:
a[0:]

array([0, 1, 2, 3])

In [19]:
a[1:]

array([1, 2, 3])

In [20]:
a[:1]

array([0])

In [21]:
a[[-3]]

array([1])

In [22]:
a[:-1]

array([0, 1, 2])

In [23]:
a[::2]

array([0, 2])

In [24]:
a[1::2]

array([1, 3])

In [25]:
a = np.array([0,1,2,3])
b = np.array([0.0,0.1,0.2,0.3])

In [26]:
type(a)

numpy.ndarray

In [27]:
a.dtype

dtype('int32')

In [28]:
b.dtype

dtype('float64')

In [29]:
c = np.array([0,1.1,2,3.8],dtype=float)
c

array([0. , 1.1, 2. , 3.8])

In [30]:
d = np.array([0,1.1,2,3.8],dtype=int)
d

array([0, 1, 2, 3])

In [31]:
d.dtype

dtype('int32')

In [32]:
a = np.array([0,2,3,4])

In [33]:
a.shape

(4,)

In [34]:
A = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
A.shape

(3, 4)

In [36]:
B = np.array([
    [
        [0,1],
        [2,3],
        [4,5]
    ],
    [
        [6,7],
        [8,9],
        [10,11]
    ]
])
B

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [37]:
B.shape

(2, 3, 2)

In [38]:
B.ndim

3

In [40]:
B.size

12

In [41]:
A = np.array([
    [0,1,2,3],
    [4,5,6,7]
])
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
A.shape

(2, 4)

In [43]:
A[0]

array([0, 1, 2, 3])

In [47]:
A[1]

array([4, 5, 6, 7])

In [48]:
A[:0]

array([], shape=(0, 4), dtype=int32)

In [49]:
A[:1]

array([[0, 1, 2, 3]])

In [50]:
A[:,0]

array([0, 4])

In [51]:
A[:,3]

array([3, 7])

In [52]:
A[0,0]

0

In [53]:
A[1,3]

7

In [54]:
A[:,1:3]

array([[1, 2],
       [5, 6]])

In [55]:
A[0] = np.array([8,9,10,11])
A

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [57]:
A[1] = 98
A

array([[ 8,  9, 10, 11],
       [98, 98, 98, 98]])

In [60]:
a = np.array([0,1,2,4])
a

array([0, 1, 2, 4])

In [61]:
a.sum()

7

In [62]:
a.mean()

1.75

In [63]:
a.std()

1.479019945774904

In [64]:
a.var()

2.1875

In [65]:
a.max()

4

In [66]:
a.min()

0

In [67]:
A = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
A.sum()

66

In [69]:
A.mean()

5.5

In [70]:
A.std()

3.452052529534663

In [71]:
A.var()

11.916666666666666

In [72]:
A.max()

11

In [73]:
A.min()

0

In [74]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [75]:
A.sum(axis=1)

array([ 6, 22, 38])

In [76]:
A.mean(axis=0)

array([4., 5., 6., 7.])

In [78]:
A.mean(axis=1)

array([1.5, 5.5, 9.5])

In [79]:
A = np.array([
    [0,1,2],
    [3,4,5]
])

B = np.array([
    [6,7,8],
    [9,10,11]
])

In [80]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [82]:
A + B

array([[ 6,  8, 10],
       [12, 14, 16]])

In [83]:
A - B

array([[-6, -6, -6],
       [-6, -6, -6]])

In [84]:
A * B

array([[ 0,  7, 16],
       [27, 40, 55]])

In [85]:
B.T

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [87]:
A @ B.T

array([[ 23,  32],
       [ 86, 122]])

In [88]:
A.T @ B

array([[27, 30, 33],
       [42, 47, 52],
       [57, 64, 71]])

In [89]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [92]:
np.arange(5,10,2)

array([5, 7, 9])

In [93]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [95]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
np.random.randint(0,10,(10))

array([3, 7, 9, 9, 9, 6, 6, 5, 2, 3])

In [98]:
np.random.randint(0,10,(5,2))

array([[7, 2],
       [1, 6],
       [8, 8],
       [1, 7],
       [2, 2]])

In [99]:
np.random.randint(0,10,(2,5))

array([[5, 1, 0, 2, 1],
       [3, 5, 6, 8, 0]])

In [100]:
np.random.rand(2,4)

array([[0.02151565, 0.99861237, 0.97400723, 0.75942084],
       [0.31457154, 0.75228414, 0.08155979, 0.01358571]])

In [101]:
np.random.normal(0,0.1,(10))

array([-0.0139865 ,  0.06842687, -0.12929108, -0.0295923 , -0.15200098,
        0.02902743, -0.13601017, -0.00224786,  0.03963175,  0.00542878])

In [102]:
np.random.normal(0,0.1,(2,5))

array([[ 0.1152662 , -0.06779659,  0.1818099 , -0.06693893,  0.18136133],
       [ 0.01564121, -0.20542975, -0.09636081,  0.11878266,  0.17939819]])

In [103]:
np.random.uniform(0,1,(3,4))

array([[0.55746599, 0.01557841, 0.36908095, 0.14438869],
       [0.23502712, 0.29271547, 0.12294703, 0.38960416],
       [0.13636552, 0.51128852, 0.90877654, 0.54368665]])

In [106]:
a = np.random.uniform(0,1,(2,5))
np.sort(a)

array([[0.08103833, 0.08516354, 0.44203919, 0.44470868, 0.4611661 ],
       [0.03300356, 0.19554526, 0.29518197, 0.57901522, 0.60169273]])

In [107]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [109]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])